/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.apkpure.aegon;

public final class R {
    public static final class layout {
        public static final int activity_main = 0x7f0c0001;
        public static final int activity_splash = 0x7f0c0002;
    }
    
    public static final class mipmap {
        public static final int ic_launcher = 0x7f030001;
    }
    
    public static final class style {
        public static final int AppTheme = 0x7f120009;
    }
}